version: '2.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: landslide_warehouse
    volumes:
      - landslide_warehouse:/var/lib/postgresql/data
    ports:
      - 2345:5432

  webserver:
    image: puckel/docker-airflow:1.10.4 
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=landslide_warehouse
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:123456@postgres:2345/landslide_warehouse
    volumes:
      - ../../tmp/airflow_logs:/root/airflow/logs
      - ../../tasks:/usr/local/airflow/tasks
      - ../../dags:/usr/local/airflow/dags
      - ../../datasource:/usr/local/airflow/data
    ports:
      - '8080:8080'
    command: webserver
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: puckel/docker-airflow:1.10.4 
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=landslide_warehouse
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:123456@postgres:2345/landslide_warehouse
    volumes:
      - ../../tmp/airflow_logs:/root/airflow/logs
      - ../../tasks:/usr/local/airflow/tasks
      - ../../dags:/usr/local/airflow/dags
      - ../../datasource:/usr/local/airflow/data
    command: scheduler
  executor:
    image: py_executor:1.02
    volumes:
      - ../../datasource:/app/data
      - ../../tasks:/app/tasks
      - ../../tmp/buffer:/app/buffer
    tty: true
    command: bash
volumes:
  landslide_warehouse: